/**
 * chrony NTP server config generator.
 *
 * Unlike VRRP/keepalived, chrony has no leader-election concept — every
 * node in the cluster runs it independently and serves time on its own
 * real IP. There's no priority/rank here at all: redundancy comes for free
 * by pointing clients (DHCP option 42) at every node's IP, the same way DNS
 * already gets its redundancy from DHCP option 6 listing every node.
 */

const config = require('../config');
const { pool } = require('../db');

async function getNtpConfig() {
  const { rows } = await pool.query('SELECT * FROM ntp_server_config LIMIT 1');
  return rows[0] || {};
}

function generateChronyConf(cfg) {
  const pool_   = cfg.upstream_pool?.length ? cfg.upstream_pool : ['0.pool.ntp.org', '1.pool.ntp.org', '2.pool.ntp.org', '3.pool.ntp.org'];
  const subnets = cfg.allowed_subnets || [];
  const stratum = cfg.local_stratum ?? 10;

  const poolLines  = pool_.map(p => `pool ${p} iburst`).join('\n');
  const allowLines = subnets.length
    ? subnets.map(s => `allow ${s}`).join('\n')
    : '# No allowed_subnets configured yet — chrony will reject every client\n# query until at least one LAN CIDR is added (ClassGuard NTP page).';

  return `# chrony.conf — generated by ClassGuard on ${new Date().toISOString()}
# Deploy to: /etc/chrony/chrony.conf (or /etc/chrony.conf on some distros)
# Install:   apt-get install chrony
# Enable:    systemctl enable --now chrony
#
# This node syncs from the public pool below and serves time to the
# subnets listed here. Run this same config on every node in the cluster —
# there's no failover/priority concept for NTP the way there is for VRRP;
# redundancy comes from clients/DHCP being told about every node's IP.

${poolLines}

# Serve time to these subnets only — deliberately NOT "allow all", which
# would turn an internet-facing host into an open NTP reflector usable in
# DDoS amplification attacks against third parties.
${allowLines}

# If every upstream pool server is briefly unreachable, still serve time to
# the LAN at this (deliberately high/untrustworthy) stratum rather than
# refusing all client requests outright.
local stratum ${stratum}

driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
`;
}

function generateInstallScript() {
  return `#!/usr/bin/env bash
# chrony install script — generated by ClassGuard
# Run on each ClassGuard node: sudo bash install-chrony.sh
set -euo pipefail

echo "Installing chrony..."
apt-get update -qq
apt-get install -y chrony

echo "Deploying ClassGuard chrony config..."
# (downloaded from ClassGuard → NTP → Server)
CONF_PATH="/etc/chrony/chrony.conf"
[[ -f /etc/chrony.conf ]] && CONF_PATH="/etc/chrony.conf"
cp chrony.conf "$CONF_PATH"

echo "Opening UDP/123 if ufw is active..."
if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
  ufw allow 123/udp
fi

echo "Starting chrony..."
systemctl enable chrony
systemctl restart chrony

echo ""
echo "Done! Verify with: chronyc sources"
`;
}

// `chronyc clients` is the only window chrony gives into who's actually
// polling it — a rolling snapshot per client (cumulative packet count since
// chronyd's last restart, seconds since its last packet), not a discrete
// log. This script polls that snapshot every 5 minutes via cron and reports
// it to ClassGuard so admins can see device activity in the UI instead of
// SSHing into each node to run `chronyc clients` by hand.
function generateClientReportScript(nodeId) {
  const apiUrl        = config.appUrl;
  const internalSecret = process.env.INTERNAL_SECRET || '';

  return `#!/usr/bin/env bash
# NTP client activity reporter — generated by ClassGuard
# Install: sudo cp ntp-client-report.sh /usr/local/bin/ && sudo chmod +x /usr/local/bin/ntp-client-report.sh
# Cron:    */5 * * * * /usr/local/bin/ntp-client-report.sh
set -euo pipefail

API_URL="${apiUrl}"
NODE_ID="${nodeId}"
SECRET="${internalSecret}"

command -v chronyc >/dev/null 2>&1 || exit 0   # chrony not installed/running — nothing to report

rows="$(chronyc -c clients 2>/dev/null || true)"
[ -z "$rows" ] && exit 0

parts=()
while IFS=',' read -r addr ntp_pkts ntp_drop _int _intl last_rx _rest; do
  case "\${addr:-}" in ''|'#'*) continue ;; esac
  # chronyc prints a literal "-" (not empty) for "never received a packet
  # yet" — bash's \${var:-default} only fires on unset/empty, so that
  # literal dash has to be caught explicitly or it ends up as invalid JSON.
  [ "$ntp_pkts" = "-" ] && ntp_pkts=0
  [ "$ntp_drop" = "-" ] && ntp_drop=0
  [ "$last_rx"  = "-" ] && last_rx=-1
  parts+=("{\\"client_address\\":\\"$addr\\",\\"ntp_packets\\":\${ntp_pkts:-0},\\"ntp_dropped\\":\${ntp_drop:-0},\\"seconds_since_last_rx\\":\${last_rx:--1}}")
done <<< "$rows"

[ \${#parts[@]} -eq 0 ] && exit 0

clients=$(IFS=,; echo "[\${parts[*]}]")

curl -fsS -m 10 -X POST "$API_URL/api/v1/ntp/internal/clients" \\
  -H "Content-Type: application/json" \\
  -H "X-Internal-Secret: $SECRET" \\
  -d "{\\"node_id\\":\\"$NODE_ID\\",\\"clients\\":$clients}" >/dev/null
`;
}

async function buildNtpBundle() {
  const cfg = await getNtpConfig();
  return {
    'chrony.conf':            generateChronyConf(cfg),
    'install-chrony.sh':      generateInstallScript(),
    'ntp-client-report.sh':   generateClientReportScript(config.node.id),
  };
}

module.exports = { getNtpConfig, generateChronyConf, generateClientReportScript, buildNtpBundle };
