/**
 * chrony NTP server config generator.
 *
 * Unlike VRRP/keepalived, chrony has no leader-election concept — every
 * node in the cluster runs it independently and serves time on its own
 * real IP. There's no priority/rank here at all: redundancy comes for free
 * by pointing clients (DHCP option 42) at every node's IP, the same way DNS
 * already gets its redundancy from DHCP option 6 listing every node.
 */

const { pool } = require('../db');

async function getNtpConfig() {
  const { rows } = await pool.query('SELECT * FROM ntp_server_config LIMIT 1');
  return rows[0] || {};
}

function generateChronyConf(cfg) {
  const pool_   = cfg.upstream_pool?.length ? cfg.upstream_pool : ['0.pool.ntp.org', '1.pool.ntp.org', '2.pool.ntp.org', '3.pool.ntp.org'];
  const subnets = cfg.allowed_subnets || [];
  const stratum = cfg.local_stratum ?? 10;

  const poolLines  = pool_.map(p => `pool ${p} iburst`).join('\n');
  const allowLines = subnets.length
    ? subnets.map(s => `allow ${s}`).join('\n')
    : '# No allowed_subnets configured yet — chrony will reject every client\n# query until at least one LAN CIDR is added (ClassGuard NTP page).';

  return `# chrony.conf — generated by ClassGuard on ${new Date().toISOString()}
# Deploy to: /etc/chrony/chrony.conf (or /etc/chrony.conf on some distros)
# Install:   apt-get install chrony
# Enable:    systemctl enable --now chrony
#
# This node syncs from the public pool below and serves time to the
# subnets listed here. Run this same config on every node in the cluster —
# there's no failover/priority concept for NTP the way there is for VRRP;
# redundancy comes from clients/DHCP being told about every node's IP.

${poolLines}

# Serve time to these subnets only — deliberately NOT "allow all", which
# would turn an internet-facing host into an open NTP reflector usable in
# DDoS amplification attacks against third parties.
${allowLines}

# If every upstream pool server is briefly unreachable, still serve time to
# the LAN at this (deliberately high/untrustworthy) stratum rather than
# refusing all client requests outright.
local stratum ${stratum}

driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
`;
}

function generateInstallScript() {
  return `#!/usr/bin/env bash
# chrony install script — generated by ClassGuard
# Run on each ClassGuard node: sudo bash install-chrony.sh
set -euo pipefail

echo "Installing chrony..."
apt-get update -qq
apt-get install -y chrony

echo "Deploying ClassGuard chrony config..."
# (downloaded from ClassGuard → NTP → Server)
CONF_PATH="/etc/chrony/chrony.conf"
[[ -f /etc/chrony.conf ]] && CONF_PATH="/etc/chrony.conf"
cp chrony.conf "$CONF_PATH"

echo "Opening UDP/123 if ufw is active..."
if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
  ufw allow 123/udp
fi

echo "Starting chrony..."
systemctl enable chrony
systemctl restart chrony

echo ""
echo "Done! Verify with: chronyc sources"
`;
}

async function buildNtpBundle() {
  const cfg = await getNtpConfig();
  return {
    'chrony.conf':         generateChronyConf(cfg),
    'install-chrony.sh':   generateInstallScript(),
  };
}

module.exports = { getNtpConfig, generateChronyConf, buildNtpBundle };
