// Encrypted export/import of this district's ClassGuard CONFIGURATION --
// policies, settings, roster, integrations, network/DHCP/RADIUS/phone
// config, etc. -- for moving to new hardware. Deliberately does NOT
// include activity history (dns_logs, browser_history, chat, audit
// trails), Kea's own internal DHCP lease/schema tables (those are
// regenerated by the existing dhcpKeaSync job from this app's own
// dhcp_subnets/dhcp_reservations tables), or cluster topology (nodes,
// ha_invite_tokens -- a restored server registers itself fresh).
//
// Restore is designed for a freshly-installed, empty server: it deletes
// then re-inserts every allowlisted table. If a table still has rows
// elsewhere referencing it (e.g. dns_logs.user_id -> users.id) that
// delete fails with a foreign-key violation BY DESIGN -- this prevents
// silently destroying an existing server's activity history just because
// someone uploaded a backup file. See restoreBackup()'s error handling.
const zlib   = require('zlib');
const crypto = require('crypto');
const { query, pool, withTransaction } = require('../db');
const config = require('../config');

const MAGIC         = 'CGBK';
const FORMAT_VERSION = 1;
const SALT_LEN = 16;
const IV_LEN   = 12;
const TAG_LEN  = 16;

// Update this list when adding a migration for a new table that holds
// admin-authored configuration (not activity history, not a synced-from-
// elsewhere cache, not Kea/cluster-internal state).
const TABLES = [
  'settings',
  'custom_roles', 'custom_role_permissions',
  'users',
  'groups', 'group_members',
  'classes', 'class_members', 'classroom_course_map',
  'policies', 'policy_assignments', 'policy_blocklists',
  'policy_category_rules', 'policy_domain_rules', 'policy_url_rules',
  // domain_categories deliberately excluded -- it's a multi-million-row
  // synced classification dataset (the actual downloaded category data
  // from category_sources' feeds), not admin-authored config, and caused
  // an OOM crash during testing. category_sources (which feeds are
  // enabled) stays; the data re-syncs via the existing categoryImport
  // scheduled job after restore.
  'blocklist_sources', 'category_sources', 'website_categories',
  'content_keywords', 'override_codes', 'allowlist_overrides',
  'bell_schedules', 'bell_schedule_periods', 'bell_schedule_assignments',
  'dns_zones', 'dns_zone_records', 'dns_records', 'dns_forward_zones',
  'locations', 'devices',
  'ip_addresses', 'ipam_sections', 'ipam_subnets',
  // ipv6_reservations deliberately excluded -- it exists on at least one
  // live install but no migration creates it (an orphaned leftover from
  // an early draft, superseded by ipv6_tunnel_config); including it here
  // would always just be a guaranteed-skipped no-op on a fresh install.
  'dhcp_subnets', 'dhcp_reservations', 'ipv6_tunnel_config',
  'vlans', 'nat_rules', 'bgp_prefixes', 'vrfs', 'multicast_groups', 'network_controllers',
  'ntp_server_config', 'ntp_servers',
  'tls_config',
  'vpn_config', 'vpn_clients',
  'radius_nas', 'radius_devices', 'radius_device_sources', 'radius_user_policies', 'radius_ha_config',
  'phones', 'phone_caller_id_profiles', 'phone_change_periods',
  'phone_change_task_templates', 'phone_change_task_template_items',
  'phone_did_numbers', 'phone_extension_rules', 'phone_paging_groups',
  'phone_parking_lots', 'phone_ring_groups',
  'oneroster_sources', 'youtube_video_rules',
  'unblock_requests', 'penalty_box', 'lesson_sessions', 'lockdown_sessions',
  'teacher_scenes',
];

// Orders TABLES so parents come before children (safe insert order) by
// reading the live FK graph from Postgres itself, rather than hand-
// maintaining 60+ tables' dependency order (error-prone, goes stale the
// moment a migration adds a new FK). Falls back to TABLES' own order for
// any table with no FK relationship to another allowlisted table.
async function getInsertOrder(client, tables) {
  const { rows: edges } = await client.query(
    `SELECT tc.table_name AS child, ccu.table_name AS parent
     FROM information_schema.table_constraints tc
     JOIN information_schema.constraint_column_usage ccu
       ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
     WHERE tc.constraint_type = 'FOREIGN KEY'
       AND tc.table_name = ANY($1) AND ccu.table_name = ANY($1)
       AND tc.table_name <> ccu.table_name`,
    [tables]
  );

  const indeg = new Map(tables.map(t => [t, 0]));
  const children = new Map(tables.map(t => [t, []]));
  for (const { child, parent } of edges) {
    children.get(parent).push(child);
    indeg.set(child, (indeg.get(child) || 0) + 1);
  }

  // Kahn's algorithm, seeded in TABLES' own order so ties stay predictable.
  const queue  = tables.filter(t => indeg.get(t) === 0);
  const order  = [];
  const seen   = new Set();
  while (queue.length) {
    const t = queue.shift();
    if (seen.has(t)) continue;
    seen.add(t);
    order.push(t);
    for (const c of children.get(t) || []) {
      indeg.set(c, indeg.get(c) - 1);
      if (indeg.get(c) === 0) queue.push(c);
    }
  }
  // Any table left out (cycle, or never reached) -- append in original
  // order rather than silently dropping it from the backup.
  for (const t of tables) if (!seen.has(t)) order.push(t);
  return order;
}

function encrypt(passphrase, plaintextBuffer) {
  const salt = crypto.randomBytes(SALT_LEN);
  const iv   = crypto.randomBytes(IV_LEN);
  const key  = crypto.scryptSync(passphrase, salt, 32);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ciphertext = Buffer.concat([cipher.update(plaintextBuffer), cipher.final()]);
  const tag = cipher.getAuthTag();
  return { salt, iv, tag, ciphertext };
}

function decrypt(passphrase, salt, iv, tag, ciphertext) {
  const key = crypto.scryptSync(passphrase, salt, 32);
  const decipher = crypto.createDecipheriv('aes-256-gcm', key, iv);
  decipher.setAuthTag(tag);
  // Throws here if the passphrase is wrong or the file is corrupted --
  // GCM's auth tag check fails closed, it never silently returns garbage.
  return Buffer.concat([decipher.update(ciphertext), decipher.final()]);
}

// File layout: MAGIC(4) | headerLen(4, BE) | header JSON (cleartext) |
// salt(16) | iv(12) | authTag(16) | ciphertext. The header is cleartext
// deliberately -- previewBackup() needs to show "created 2026-06-20,
// 41 tables, ClassGuard 0.7.30" before the admin commits to typing a
// passphrase and triggering a destructive restore.
async function createBackup(passphrase) {
  const client = await pool.connect();
  let order;
  try {
    order = await getInsertOrder(client, TABLES);
  } finally {
    client.release();
  }

  // Caught the hard way: domain_categories (a synced classification
  // dataset, since excluded from TABLES) had 5.7M rows and OOM-crashed
  // the whole API process when loaded into memory uncapped. This guard
  // turns any future repeat of that mistake into a clear, recoverable
  // error instead of a process crash.
  const MAX_ROWS_PER_TABLE = 200_000;
  const data = {};
  for (const table of order) {
    const { rows: [{ count }] } = await query(`SELECT COUNT(*) FROM ${table}`);
    if (parseInt(count, 10) > MAX_ROWS_PER_TABLE) {
      throw new Error(
        `"${table}" has ${count} rows, over the ${MAX_ROWS_PER_TABLE} safety limit for a config backup -- ` +
        `this looks like a synced/bulk dataset rather than admin-authored config and should likely be removed ` +
        `from configBackup.js's TABLES list.`
      );
    }
    const { rows } = await query(`SELECT * FROM ${table}`);
    data[table] = rows;
  }

  const header = {
    formatVersion:    FORMAT_VERSION,
    classguardVersion: config.version,
    nodeId:    config.node.id,
    createdAt: new Date().toISOString(),
    tables:    order,
    rowCounts: Object.fromEntries(order.map(t => [t, data[t].length])),
  };

  const payload  = zlib.gzipSync(Buffer.from(JSON.stringify({ insertOrder: order, data })));
  const { salt, iv, tag, ciphertext } = encrypt(passphrase, payload);

  const headerBuf = Buffer.from(JSON.stringify(header));
  const headerLen = Buffer.alloc(4);
  headerLen.writeUInt32BE(headerBuf.length);

  return Buffer.concat([Buffer.from(MAGIC), headerLen, headerBuf, salt, iv, tag, ciphertext]);
}

function parseHeader(buffer) {
  if (buffer.subarray(0, 4).toString() !== MAGIC) {
    throw new Error('Not a ClassGuard backup file');
  }
  const headerLen = buffer.readUInt32BE(4);
  const header    = JSON.parse(buffer.subarray(8, 8 + headerLen).toString());
  const rest      = buffer.subarray(8 + headerLen);
  return { header, rest };
}

// No passphrase needed -- just enough to show the admin what they're
// about to restore before asking them to commit to it.
function previewBackup(buffer) {
  const { header } = parseHeader(buffer);
  return header;
}

async function restoreBackup(buffer, passphrase) {
  const { header, rest } = parseHeader(buffer);
  if (header.formatVersion !== FORMAT_VERSION) {
    throw new Error(`Unsupported backup format version ${header.formatVersion}`);
  }

  const salt       = rest.subarray(0, SALT_LEN);
  const iv         = rest.subarray(SALT_LEN, SALT_LEN + IV_LEN);
  const tag        = rest.subarray(SALT_LEN + IV_LEN, SALT_LEN + IV_LEN + TAG_LEN);
  const ciphertext = rest.subarray(SALT_LEN + IV_LEN + TAG_LEN);

  let payload;
  try {
    payload = decrypt(passphrase, salt, iv, tag, ciphertext);
  } catch {
    throw new Error('Wrong passphrase, or this backup file is corrupted');
  }

  const { insertOrder, data } = JSON.parse(zlib.gunzipSync(payload).toString());

  // Only restore tables that exist in THIS server's current schema --
  // an older/newer backup may list a table that's since been renamed or
  // doesn't exist yet, and skipping it is far safer than failing the
  // whole restore over one table.
  const { rows: existing } = await query(
    `SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename = ANY($1)`,
    [insertOrder]
  );
  const existingSet = new Set(existing.map(r => r.tablename));
  const toRestore    = insertOrder.filter(t => existingSet.has(t));

  // Object-shaped values need different serialization depending on the
  // REAL column type, not their JS runtime shape -- a jsonb column needs
  // JSON.stringify, but a native Postgres array column (e.g. text[] for
  // ntp_server_config's server list) needs the bare JS array handed to
  // the pg driver as-is, or it sends a JSON string where Postgres expects
  // an array literal ("malformed array literal", caught in testing).
  const { rows: columnTypes } = await query(
    `SELECT table_name, column_name, data_type
     FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = ANY($1)`,
    [toRestore]
  );
  const arrayColumns = new Set(
    columnTypes.filter(c => c.data_type === 'ARRAY').map(c => `${c.table_name}.${c.column_name}`)
  );

  await withTransaction(async (client) => {
    // Children-before-parents for delete, parents-before-children for
    // insert -- both directions of the same dependency order.
    for (const table of [...toRestore].reverse()) {
      try {
        await client.query(`DELETE FROM ${table}`);
      } catch (err) {
        if (err.code === '23503') {
          throw new Error(
            `Restore stopped at "${table}" -- this server already has data referencing existing rows in it ` +
            `(foreign key violation). Restore is intended for a freshly-installed server with no existing ` +
            `activity history; restoring onto a server that's already in use isn't supported.`,
            { cause: err }
          );
        }
        throw err;
      }
    }

    for (const table of toRestore) {
      const rows = data[table] || [];
      if (rows.length === 0) continue;
      const columns = Object.keys(rows[0]);
      const colList = columns.map(c => `"${c}"`).join(', ');
      // Postgres caps a single query at 65535 parameters -- a wide table
      // with thousands of rows (e.g. users) could exceed that in one
      // INSERT, so chunk rows to stay safely under the limit instead.
      const rowsPerBatch = Math.max(1, Math.floor(60000 / columns.length));

      for (let start = 0; start < rows.length; start += rowsPerBatch) {
        const batch = rows.slice(start, start + rowsPerBatch);
        const valuesSql = batch.map((_, i) =>
          `(${columns.map((_, j) => `$${i * columns.length + j + 1}`).join(', ')})`
        ).join(', ');
        // jsonb/json columns round-tripped through gzip+JSON come back as
        // plain JS objects/arrays -- stringify explicitly rather than
        // relying on the driver to infer that's what a bare object means.
        // Native Postgres array columns are the one exception (see above).
        const params = batch.flatMap(row => columns.map(c => {
          const v = row[c];
          if (v === null || typeof v !== 'object') return v;
          return arrayColumns.has(`${table}.${c}`) ? v : JSON.stringify(v);
        }));
        await client.query(`INSERT INTO ${table} (${colList}) VALUES ${valuesSql}`, params);
      }
    }
  });

  return { restoredTables: toRestore, skippedTables: insertOrder.filter(t => !existingSet.has(t)) };
}

module.exports = { TABLES, createBackup, previewBackup, restoreBackup };
