/**
 * Hurricane Electric 6in4 tunnel config generator — for districts whose ISP
 * doesn't offer native IPv6 (this one doesn't; districts that do have native
 * IPv6 simply leave this disabled). Same host-level pattern as chrony.js/
 * keepalived.js: ClassGuard generates config + an install script, the admin
 * runs it on the host (a SIT tunnel interface isn't something that fits in
 * a normal Docker container any better than VRRP does), and a cron script
 * reports health back the same way ntp-client-report.sh does.
 *
 * ClassGuard terminates the tunnel as the IPv6 *uplink* only — it does not
 * become the LAN's IPv6 router. The routed_prefix/local_ipv6 this generates
 * are the two values an admin manually enters as a static route in UniFi
 * (UniFi's API here is read-only, confirmed against services/network/
 * unifi.js — this one step can't be automated), so UniFi keeps doing RA/
 * SLAAC distribution to the LAN itself, exactly as it already does for IPv4.
 */

const config = require('../config');
const { pool } = require('../db');

async function getTunnelConfig() {
  const { rows } = await pool.query('SELECT * FROM ipv6_tunnel_config LIMIT 1');
  return rows[0] || {};
}

function generateSetupScript(cfg) {
  return `#!/usr/bin/env bash
# IPv6 tunnel setup — generated by ClassGuard. Idempotent: safe to re-run
# after a config change (removes the old interface first).
set -euo pipefail

TUNNEL_IF="he-ipv6"

if ip link show "$TUNNEL_IF" &>/dev/null; then
  ip link set "$TUNNEL_IF" down
  ip tunnel del "$TUNNEL_IF"
fi

ip tunnel add "$TUNNEL_IF" mode sit remote ${cfg.he_server_ipv4} local ${cfg.he_client_ipv4} ttl 255
ip link set "$TUNNEL_IF" up
ip addr add ${cfg.local_ipv6}/64 dev "$TUNNEL_IF"
ip route add ::/0 dev "$TUNNEL_IF"

echo "Tunnel $TUNNEL_IF up. Verify with: ping6 -c3 ipv6.google.com"
`;
}

function generateInstallScript() {
  return `#!/usr/bin/env bash
# IPv6 tunnel install script — generated by ClassGuard
# Run on the node terminating the tunnel: sudo bash install-ipv6-tunnel.sh
set -euo pipefail

echo "Installing tunnel setup script..."
install -m 755 setup-ipv6-tunnel.sh /usr/local/bin/setup-ipv6-tunnel.sh

echo "Installing systemd unit (runs the setup script at boot, after networking is up)..."
cat > /etc/systemd/system/classguard-ipv6-tunnel.service <<'EOF'
[Unit]
Description=ClassGuard Hurricane Electric IPv6 tunnel
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/setup-ipv6-tunnel.sh

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now classguard-ipv6-tunnel.service

if [[ -f ipv6-health-report.sh ]]; then
  echo "Installing the health-check reporter (cron, every 5 min)..."
  cp ipv6-health-report.sh /usr/local/bin/ipv6-health-report.sh
  chmod +x /usr/local/bin/ipv6-health-report.sh
  cron_line="*/5 * * * * /usr/local/bin/ipv6-health-report.sh"
  (crontab -l 2>/dev/null | grep -vF "ipv6-health-report.sh"; echo "$cron_line") | crontab -
fi

echo ""
echo "Done! Verify with: ip -6 addr show he-ipv6"
echo "Then add a static route in UniFi (destination/next-hop shown on the IPv6 page) so the LAN can actually use this."
`;
}

// Reports whether the tunnel interface is actually up and has working IPv6
// reachability — a tunnel interface existing isn't the same as it working
// (HE's side can reject/drop it for several reasons unrelated to local
// config), so this actually pings out rather than just checking link state.
function generateHealthCheckScript(nodeId) {
  const apiUrl = config.appUrl;
  const internalSecret = process.env.INTERNAL_SECRET || '';

  return `#!/usr/bin/env bash
# IPv6 tunnel health reporter — generated by ClassGuard
# Install: sudo cp ipv6-health-report.sh /usr/local/bin/ && sudo chmod +x /usr/local/bin/ipv6-health-report.sh
# Cron:    */5 * * * * /usr/local/bin/ipv6-health-report.sh
set -uo pipefail

API_URL="${apiUrl}"
NODE_ID="${nodeId}"
SECRET="${internalSecret}"

status="down"
if ip link show he-ipv6 &>/dev/null && ping6 -c2 -W3 ipv6.google.com &>/dev/null; then
  status="up"
fi

curl -fsS -m 10 -X POST "$API_URL/api/v1/ipv6/internal/status" \\
  -H "Content-Type: application/json" \\
  -H "X-Internal-Secret: $SECRET" \\
  -d "{\\"node_id\\":\\"$NODE_ID\\",\\"status\\":\\"$status\\"}" >/dev/null
`;
}

async function buildBundle() {
  const cfg = await getTunnelConfig();
  return {
    'setup-ipv6-tunnel.sh':   generateSetupScript(cfg),
    'install-ipv6-tunnel.sh': generateInstallScript(),
    'ipv6-health-report.sh':  generateHealthCheckScript(config.node.id),
  };
}

module.exports = { getTunnelConfig, generateSetupScript, buildBundle };
