/**
 * Keepalived / VRRP config generator.
 *
 * Architecture:
 *   - Each ClassGuard node has its own real IP (used for DNS — both IPs are
 *     listed in DHCP option 6 so DNS is natively redundant).
 *   - The VIP floats between nodes via VRRP and is used for:
 *       RADIUS (1812/1813), DHCP (67), ClassGuard web UI (80/443)
 *   - Keepalived monitors FreeRADIUS health and demotes if the process dies.
 *   - Switches/APs should ALSO be configured with the secondary node's real IP
 *     as a fallback RADIUS server (belt-and-suspenders, sub-5s failover).
 */

const { pool } = require('../db');

async function getHaConfig() {
  const { rows } = await pool.query('SELECT * FROM radius_ha_config LIMIT 1');
  return rows[0] || {};
}

async function getNodes() {
  const { rows } = await pool.query(
    `SELECT id, hostname, api_url, ha_role FROM nodes ORDER BY ha_role`
  );
  return rows;
}

function generateKeepalived(cfg, isPrimary) {
  const vip     = cfg.vip_address    || 'YOUR_VIP_ADDRESS';
  const prefix  = cfg.vip_prefix_len || 24;
  const iface   = cfg.vip_interface  || 'eth0';
  const inst    = cfg.vrrp_instance_name     || 'CLASSGUARD_APPS';
  const vrid    = cfg.vrrp_virtual_router_id || 51;
  const advt    = cfg.vrrp_advert_int        || 1;
  const authpw  = cfg.vrrp_auth_password     || 'CHANGE_ME';
  const prio    = isPrimary
    ? (cfg.priority_primary   || 150)
    : (cfg.priority_secondary || 100);

  // Health checks are opt-in per service so a school running only the web UI
  // (no FreeRADIUS) doesn't fail over on a check for a process that's never running.
  const trackApi     = cfg.track_classguard_api !== false; // default on
  const trackRadius  = cfg.track_freeradius === true;      // default off

  const scripts = [];
  if (trackApi) {
    scripts.push({
      name: 'check_classguard_api',
      block: `vrrp_script check_classguard_api {
    script "curl -sf http://localhost:3001/health -o /dev/null"
    interval 2
    weight   -60    # drop priority by 60 if the ClassGuard API is unreachable → triggers failover
    rise     2
    fall     2
}`,
    });
  }
  if (trackRadius) {
    scripts.push({
      name: 'check_freeradius',
      block: `vrrp_script check_freeradius {
    script "pidof freeradius"
    interval 2
    weight   -60    # drop priority by 60 if FreeRADIUS is down → triggers failover
    rise     2
    fall     2
}`,
    });
  }

  const scriptBlocks = scripts.map(s => s.block).join('\n\n');
  const trackScript  = scripts.length
    ? `\n    track_script {\n${scripts.map(s => `        ${s.name}`).join('\n')}\n    }\n`
    : '';

  return `# Keepalived configuration — ClassGuard ${isPrimary ? 'PRIMARY' : 'SECONDARY'} node
# Generated by ClassGuard on ${new Date().toISOString()}
#
# Deploy to: /etc/keepalived/keepalived.conf
# Install:   apt-get install keepalived
# Enable:    systemctl enable --now keepalived
#
# IP layout:
#   Primary real IP  : used for DNS (DHCP option 6 lists both real IPs)
#   Secondary real IP: used for DNS + direct RADIUS fallback on switches/APs
#   VIP (${vip}): ClassGuard UI${trackRadius ? ', RADIUS, DHCP' : ''} — floats between nodes
#   This is also the single hostname/IP a TLS certificate should be issued for —
#   it never needs to move with the active node, so one cert (and one public DNS
#   record) covers the whole cluster.

global_defs {
   router_id CLASSGUARD_${isPrimary ? 'PRIMARY' : 'SECONDARY'}
   script_user root
   enable_script_security
}
${scriptBlocks ? '\n' + scriptBlocks + '\n' : ''}
vrrp_instance ${inst} {
    state     ${isPrimary ? 'MASTER' : 'BACKUP'}
    interface ${iface}
    virtual_router_id ${vrid}
    priority  ${prio}
    advert_int ${advt}

    authentication {
        auth_type PASS
        auth_pass ${authpw}
    }

    virtual_ipaddress {
        ${vip}/${prefix} dev ${iface}
    }
${trackScript}
    # Notify ClassGuard when role changes
    notify_master  "/etc/keepalived/notify.sh MASTER"
    notify_backup  "/etc/keepalived/notify.sh BACKUP"
    notify_fault   "/etc/keepalived/notify.sh FAULT"
}
`;
}

function generateNotifyScript(apiUrl) {
  return `#!/bin/bash
# /etc/keepalived/notify.sh
# Notifies ClassGuard API when this node's VRRP role changes.
STATE=$1
API="${apiUrl || 'http://localhost:3001'}"
TOKEN=$(grep '^INTERNAL_SECRET=' /opt/classguard/.env 2>/dev/null | cut -d= -f2-)
NODE_ID=$(grep '^NODE_ID=' /opt/classguard/.env 2>/dev/null | cut -d= -f2-)

curl -sf -X POST "$API/api/v1/ha/vrrp-notify" \\
  -H "Content-Type: application/json" \\
  -H "X-Internal-Secret: $TOKEN" \\
  -d "{\\"state\\":\\"$STATE\\",\\"node_id\\":\\"$NODE_ID\\"}" || true

logger "ClassGuard VRRP state changed to $STATE on node $NODE_ID"
`;
}

function generateFreeRadiusClients(nasRows) {
  const blocks = nasRows.map(n => `
client ${n.shortname} {
    ipaddr  = ${n.ip_address}
    secret  = ${n.shared_secret}
    vendor  = ${n.vendor === 'other' ? 'cisco' : n.vendor}
    # ${n.name}${n.description ? ' — ' + n.description : ''}
}`).join('\n');

  return `# FreeRADIUS clients.conf — generated by ClassGuard
# Deploy to: /etc/freeradius/3.0/clients.conf
# Regenerate any time you add/remove NAS clients in ClassGuard.
${blocks}
`;
}

function generateFreeRadiusRestMod(apiUrl, internalSecret) {
  return `# FreeRADIUS rlm_rest module — generated by ClassGuard
# Deploy to: /etc/freeradius/3.0/mods-available/rest
# Enable:    ln -s ../mods-available/rest mods-enabled/rest

rest {
    connect_uri = "${apiUrl || 'http://localhost:3001'}"

    connect_timeout = 4.0
    timeout         = 8.0

    # Authorization phase — MAB device check OR user lookup
    authorize {
        uri    = "\${..connect_uri}/api/v1/radius/authorize"
        method = 'post'
        body   = 'json'
        tls    = \${..tls}
        # Pass the internal secret header
        header {
            X-Internal-Secret = "${internalSecret || ''}"
        }
    }

    # Authentication phase — EAP-TTLS/PAP → Google Secure LDAP
    authenticate {
        uri    = "\${..connect_uri}/api/v1/radius/authenticate"
        method = 'post'
        body   = 'json'
        tls    = \${..tls}
        header {
            X-Internal-Secret = "${internalSecret || ''}"
        }
    }

    # Accounting — session tracking
    accounting {
        uri    = "\${..connect_uri}/api/v1/radius/accounting"
        method = 'post'
        body   = 'json'
        tls    = \${..tls}
        header {
            X-Internal-Secret = "${internalSecret || ''}"
        }
    }

    tls {
        # Uncomment if ClassGuard uses HTTPS and has a self-signed cert:
        # check_cert = no
    }

    pool {
        start    = 5
        min      = 4
        max      = 32
        spare    = 3
        uses     = 0
        lifetime = 0
        idle_timeout = 60
    }
}
`;
}

function generateFreeRadiusVirtualServer() {
  return `# FreeRADIUS virtual server — generated by ClassGuard
# Deploy to: /etc/freeradius/3.0/sites-available/classguard
# Enable:    ln -s ../sites-available/classguard sites-enabled/classguard
# Disable:   rm sites-enabled/default sites-enabled/inner-tunnel
#
# Auth flow:
#   EAP-TTLS/PAP (user WiFi via Google Workspace):
#     authorize  → ClassGuard looks up user, sets Auth-Type = rest
#     authenticate (inner-tunnel PAP) → ClassGuard validates via Google Secure LDAP
#
#   MAB (device WiFi — Calling-Station-Id = MAC address):
#     authorize  → ClassGuard checks radius_devices → Accept/Reject + VLAN attrs

server classguard {
    listen {
        type      = auth
        ipaddr    = *
        port      = 1812
        limit { max_connections = 256 }
    }

    listen {
        type      = acct
        ipaddr    = *
        port      = 1813
        limit { max_connections = 64 }
    }

    authorize {
        # Detect MAB: User-Name looks like a MAC address
        if (&User-Name =~ /^([0-9a-f]{2}[:-]?){5}[0-9a-f]{2}$/i) {
            update control { Auth-Type := Accept }
            rest  # ClassGuard MAB check
        } else {
            eap { ok = return }
            rest  # ClassGuard user lookup
        }
    }

    authenticate {
        Auth-Type rest {
            rest
        }
        Auth-Type eap {
            eap
        }
    }

    accounting {
        rest
    }

    session { }
    post-auth {
        if (reply:Tunnel-Type == 'VLAN') {
            update reply {
                Tunnel-Medium-Type = IEEE-802
            }
        }
        Post-Auth-Type REJECT { }
    }
}

server inner-tunnel {
    listen {
        ipaddr    = 127.0.0.1
        port      = 18120
        type      = auth
    }

    authorize {
        rest
        pap
    }

    authenticate {
        Auth-Type PAP {
            rest  # sends cleartext password to ClassGuard → Google Secure LDAP
        }
    }
}
`;
}

function generateEapMod() {
  return `# FreeRADIUS EAP module config — generated by ClassGuard
# Deploy to: /etc/freeradius/3.0/mods-available/eap
# (replaces the default eap module config)
#
# EAP-TTLS/PAP is the recommended method:
#   - Works on iOS without any profile (auto-negotiated)
#   - Works on Android when WiFi profile pushed via MDM or manually configured
#   - Works on macOS, Windows, ChromeOS
#   - No MSCHAPv2 needed → no NTLM hash issues with Google passwords

eap {
    default_eap_type = ttls

    timer_expire    = 60
    ignore_unknown_eap_types = no
    cisco_accounting_username_bug = no
    max_sessions = 4096

    tls-config tls-common {
        # Generate with: openssl req -x509 -newkey rsa:4096 -keyout /etc/freeradius/3.0/certs/server.key
        #                        -out /etc/freeradius/3.0/certs/server.crt -days 3650 -nodes
        private_key_file   = \${cadir}/certs/server.key
        certificate_file   = \${cadir}/certs/server.crt
        ca_file            = \${cadir}/certs/ca.crt
        dh_file            = \${cadir}/certs/dh
        cipher_list        = "HIGH"
        tls_min_version    = "1.2"
        ecdh_curve         = "prime256v1"
        cache { enable = yes  lifetime = 24 max_entries = 255 }
    }

    ttls {
        tls          = tls-common
        # Inner method is PAP — ClassGuard receives the cleartext password
        # and validates it against Google Secure LDAP
        default_eap_type     = md5
        copy_request_to_tunnel = yes
        use_tunneled_reply     = yes
        virtual_server         = "inner-tunnel"
    }

    # Keep peap for legacy Windows devices (optional)
    peap {
        tls              = tls-common
        default_eap_type = mschapv2
        copy_request_to_tunnel = yes
        use_tunneled_reply     = yes
        virtual_server         = "inner-tunnel"
    }
}
`;
}

function generateInstallScript(apiUrl) {
  return `#!/usr/bin/env bash
# FreeRADIUS install + ClassGuard integration script
# Run on each ClassGuard node: sudo bash install-freeradius.sh
set -euo pipefail

API_URL="${apiUrl || 'http://localhost:3001'}"
FR_DIR="/etc/freeradius/3.0"

echo "Installing FreeRADIUS 3..."
apt-get update -qq
apt-get install -y freeradius freeradius-rest keepalived

echo "Deploying ClassGuard config files..."
# (You downloaded these from ClassGuard → RADIUS → HA & Config)
cp clients.conf        $FR_DIR/clients.conf
cp rest                $FR_DIR/mods-available/rest
cp eap                 $FR_DIR/mods-available/eap
cp classguard          $FR_DIR/sites-available/classguard

ln -sf $FR_DIR/mods-available/rest   $FR_DIR/mods-enabled/rest
ln -sf $FR_DIR/sites-available/classguard $FR_DIR/sites-enabled/classguard
rm -f  $FR_DIR/sites-enabled/default $FR_DIR/sites-enabled/inner-tunnel

echo "Generating TLS certificate for EAP..."
mkdir -p $FR_DIR/certs
if [[ ! -f $FR_DIR/certs/server.crt ]]; then
  openssl req -x509 -newkey rsa:4096 \\
    -keyout $FR_DIR/certs/server.key \\
    -out    $FR_DIR/certs/server.crt \\
    -days   3650 -nodes \\
    -subj   "/CN=ClassGuard RADIUS/O=School District"
  openssl dhparam -out $FR_DIR/certs/dh 2048
  cp $FR_DIR/certs/server.crt $FR_DIR/certs/ca.crt
  chmod 640 $FR_DIR/certs/server.key
  chown root:freerad $FR_DIR/certs/server.key
fi

echo "Deploying Keepalived config..."
cp keepalived.conf /etc/keepalived/keepalived.conf
cp notify.sh       /etc/keepalived/notify.sh
chmod +x /etc/keepalived/notify.sh

echo "Starting services..."
systemctl enable freeradius keepalived
systemctl restart freeradius keepalived

echo ""
echo "Done! Verify FreeRADIUS: radiusd -X"
echo "Test auth:  echo 'User-Name = test@school.edu, User-Password = wrong' | radtest test@school.edu wrong localhost 0 testing123"
`;
}

async function buildConfigBundle() {
  const cfg    = await getHaConfig();
  const nodes  = await getNodes();
  const { rows: nasRows } = await pool.query(
    'SELECT * FROM radius_nas WHERE is_active = true ORDER BY shortname'
  );

  const apiUrl        = process.env.APP_URL || 'http://localhost:3001';
  const internalSecret = process.env.INTERNAL_SECRET || '';

  return {
    'clients.conf':     generateFreeRadiusClients(nasRows),
    'rest':             generateFreeRadiusRestMod(apiUrl, internalSecret),
    'classguard':       generateFreeRadiusVirtualServer(),
    'eap':              generateEapMod(),
    'keepalived-primary.conf':   generateKeepalived(cfg, true),
    'keepalived-secondary.conf': generateKeepalived(cfg, false),
    'notify.sh':        generateNotifyScript(apiUrl),
    'install-freeradius.sh':     generateInstallScript(apiUrl),
  };
}

// VIP/VRRP files only — for districts that don't run FreeRADIUS through ClassGuard
async function buildVrrpOnlyBundle() {
  const cfg    = await getHaConfig();
  const apiUrl = process.env.APP_URL || 'http://localhost:3001';

  return {
    'keepalived-primary.conf':   generateKeepalived(cfg, true),
    'keepalived-secondary.conf': generateKeepalived(cfg, false),
    'notify.sh':                 generateNotifyScript(apiUrl),
  };
}

module.exports = { buildConfigBundle, buildVrrpOnlyBundle, getHaConfig };
