#!/usr/bin/env python3
"""
Bootstraps and supervises this node's StrongSwan config from ClassGuard's
own API, and reports session status back. Runs as PID 1 (entrypoint.sh
backgrounds charon and execs this script) inside a network_mode: host
container, so the API is reached at 127.0.0.1:3001 — the same path
keepalived's host-level health check already uses, since this container,
like keepalived, isn't on the classguard-net bridge network.

Why one script does config-render AND status-push AND a debug HTTP server:
this is a small, single-purpose sidecar to charon, not an app — splitting
it into three cooperating processes would just be more to keep in sync for
no real benefit here.
"""
import hashlib
import http.server
import json
import os
import shutil
import subprocess
import threading
import time
import urllib.request

API_BASE = "http://127.0.0.1:3001/api/v1/vpn"
SECRET = os.environ.get("INTERNAL_SECRET", "")
CERT_DIR = "/certs"  # tls-certs volume, read-only
POLL_SECONDS = 30

_last_config_hash = None
_last_sessions = []
_lock = threading.Lock()


def api_request(path, method="GET", body=None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(
        f"{API_BASE}{path}", data=data, method=method,
        headers={"X-Internal-Secret": SECRET, "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())


def render_swanctl_conf(cfg):
    pool_cidr = cfg.get("client_subnet") or "10.99.99.0/24"
    dns_servers = ",".join(cfg.get("dns_servers") or [])
    restrict = cfg.get("restrict_to_subnets") or []
    local_ts = ",".join(restrict) if restrict else "0.0.0.0/0"

    dns_line = f"\n        dns = {dns_servers}" if dns_servers else ""

    return f"""\
# Generated by vpn-agent.py — do not edit directly, edit via ClassGuard's VPN page
connections {{
    staff-vpn {{
        version = 2
        local_addrs = %any
        remote_addrs = %any
        proposals = default
        send_certreq = no
        local {{
            auth = pubkey
            certs = server.pem
        }}
        remote {{
            auth = pubkey
            cacerts = classguard-ca.pem
        }}
        children {{
            net {{
                local_ts = {local_ts}
                rekey_time = 0s
                dpd_action = clear
                esp_proposals = default
            }}
        }}
        pools = staff-pool
    }}
}}

pools {{
    staff-pool {{
        addrs = {pool_cidr}{dns_line}
    }}
}}

secrets {{
    private-server {{
        file = server.key
    }}
}}
"""


def ensure_routing(client_subnet):
    """Idempotent: enable IP forwarding and NAT the VPN pool out the host's
    default route, so a connected client can reach other LAN devices without
    requiring any change to the school's actual switches/routers."""
    subprocess.run(["sysctl", "-w", "net.ipv4.ip_forward=1"], check=False)
    check = subprocess.run(
        ["iptables", "-t", "nat", "-C", "POSTROUTING", "-s", client_subnet, "-j", "MASQUERADE"],
        stderr=subprocess.DEVNULL,
    )
    if check.returncode != 0:
        subprocess.run(
            ["iptables", "-t", "nat", "-A", "POSTROUTING", "-s", client_subnet, "-j", "MASQUERADE"],
            check=False,
        )


def apply_config(cfg):
    global _last_config_hash

    if not cfg.get("enabled") or not cfg.get("ca_cert_pem"):
        # Nothing loaded into swanctl — charon stays up and listening, but
        # with zero connections configured, so it can't accept any tunnel.
        # ca_cert_pem is ClassGuard's own CA (services/ca.js), generated via
        # the VPN page's "Generate CA" button — the same CA the SCEP server
        # (infrastructure/scep/) issues client certs from. Not Mosyle's own
        # cert; Mosyle never had one to give (see migration 053).
        return

    config_hash = hashlib.sha256(json.dumps(cfg, sort_keys=True).encode()).hexdigest()
    if config_hash == _last_config_hash:
        return  # no change since last successful apply

    os.makedirs("/etc/swanctl/x509ca", exist_ok=True)
    os.makedirs("/etc/swanctl/x509", exist_ok=True)
    os.makedirs("/etc/swanctl/private", exist_ok=True)
    os.makedirs("/etc/swanctl/conf.d", exist_ok=True)

    with open("/etc/swanctl/x509ca/classguard-ca.pem", "w") as f:
        f.write(cfg["ca_cert_pem"])

    # fullchain.pem (leaf + intermediates) is fine to drop straight into the
    # x509 cert dir as-is — swanctl loads every cert it finds there and
    # matches the right one by subject, same way nginx already consumes
    # this exact file unmodified.
    shutil.copyfile(f"{CERT_DIR}/fullchain.pem", "/etc/swanctl/x509/server.pem")
    shutil.copyfile(f"{CERT_DIR}/privkey.pem", "/etc/swanctl/private/server.key")
    os.chmod("/etc/swanctl/private/server.key", 0o600)

    with open("/etc/swanctl/conf.d/staff-vpn.conf", "w") as f:
        f.write(render_swanctl_conf(cfg))

    ensure_routing(str(cfg.get("client_subnet") or "10.99.99.0/24"))

    result = subprocess.run(["swanctl", "--load-all"], capture_output=True, text=True)
    print(f"[vpn-agent] swanctl --load-all: {result.stdout.strip()} {result.stderr.strip()}", flush=True)
    _last_config_hash = config_hash


def parse_sas():
    """swanctl --list-sas --raw emits one semicolon/colon-delimited line per
    established SA — not JSON, this is its actual native machine-readable
    format."""
    result = subprocess.run(["swanctl", "--list-sas", "--raw"], capture_output=True, text=True)
    sessions = []
    for line in result.stdout.strip().splitlines():
        if not line:
            continue
        fields = dict(
            pair.split("=", 1) for pair in line.split(":") if "=" in pair
        )
        if not fields:
            continue  # e.g. the literal "list-sas reply {}" marker line when there are zero SAs
        sessions.append({
            "cert_cn": fields.get("remote-id", fields.get("identity", "unknown")),
            "assigned_ip": fields.get("vip", fields.get("local-vip")),
            "real_ip": fields.get("remote-host"),
            "bytes_in": int(fields.get("bytes-in", 0) or 0),
            "bytes_out": int(fields.get("bytes-out", 0) or 0),
            "established_seconds": int(fields.get("established", 0) or 0),
        })
    return sessions


def poll_loop():
    global _last_sessions
    while True:
        try:
            cfg = api_request("/bootstrap")
            apply_config(cfg)
        except Exception as e:
            print(f"[vpn-agent] bootstrap fetch/apply failed: {e}", flush=True)

        try:
            sessions = parse_sas()
            with _lock:
                _last_sessions = sessions
            api_request("/internal/sessions", method="POST", body={"sessions": sessions})
        except Exception as e:
            print(f"[vpn-agent] session list/push failed: {e}", flush=True)

        time.sleep(POLL_SECONDS)


class StatusHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path != "/status":
            self.send_response(404)
            self.end_headers()
            return
        with _lock:
            body = json.dumps({"sessions": _last_sessions}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass  # quiet — this is a debug endpoint, not worth log noise


def main():
    threading.Thread(
        target=lambda: http.server.HTTPServer(("0.0.0.0", 9999), StatusHandler).serve_forever(),
        daemon=True,
    ).start()
    poll_loop()


if __name__ == "__main__":
    main()
